I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 446, in script
    show julia happy highlight:
Exception: Image 'julia happy' does not accept attributes 'highlight'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 446, in script
    show julia happy highlight:
  File "D:\renpy-8.0.3-sdk\renpy\renpy\ast.py", line 1408, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "D:\renpy-8.0.3-sdk\renpy\renpy\ast.py", line 1371, in show_imspec
    renpy.config.show(name,
  File "D:\renpy-8.0.3-sdk\renpy\renpy\exports.py", line 686, in show
    if not base.find_target() and renpy.config.missing_show:
  File "D:\renpy-8.0.3-sdk\renpy\renpy\display\image.py", line 414, in find_target
    self.target = target._duplicate(a)
  File "D:\renpy-8.0.3-sdk\renpy\renpy\display\core.py", line 397, in _duplicate
    args.extraneous()
  File "D:\renpy-8.0.3-sdk\renpy\renpy\display\core.py", line 265, in extraneous
    raise Exception("Image '{}' does not accept attributes '{}'.".format(
Exception: Image 'julia happy' does not accept attributes 'highlight'.

Windows-10-10.0.22000 AMD64
Ren'Py 8.0.3.22090809
Capybara 1.0
Sat Dec 31 15:24:55 2022
